AWSTemplateFormatVersion: 2010-09-09
Description: DeployStack CFN template translated from Docker compose
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
  SubnetA:
    Type: AWS::EC2::Subnet::Id
  SubnetB:
    Type: AWS::EC2::Subnet::Id
  ServiceName:
    Type: String
    Default: DeployStackService
Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Join ['', [!Ref ServiceName, Cluster]]
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [!Ref ServiceName, ExecutionRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  LogGroupteedy-server:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', [/ecs/, !Ref ServiceName, TaskDefinitionteedy-server]]
  TaskDefinitionteedy-server:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - LogGroupteedy-server
    Properties:
      Family: !Join ['', [!Ref ServiceName, TaskDefinitionteedy-server]]
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 512
      Memory: 1GB
      ExecutionRoleArn: !Ref ExecutionRole
      ContainerDefinitions:
        - Name: teedy-server
          Image: docker.io/sismics/docs:v1.10
          ReadonlyRootFilesystem: false
          PortMappings:
            - ContainerPort: 8080
          Environment:
            - name: DOCS_BASE_URL
              value: https://docs.example.com
            - name: DOCS_ADMIN_EMAIL_INIT
              value: admin@example.com
            - name: DOCS_ADMIN_PASSWORD_INIT
              value: $$2a$$05$$PcMNUbJvsk7QHFSfEIDaIOjk1VI9/E7IPjTKx.jkjPxkx2EOKSoPS
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroupteedy-server
              awslogs-stream-prefix: ecs
  ContainerSecurityGroupteedy-server:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['', [teedy-server, ContainerSecurityGroup]]
      VpcId: !Ref VPC
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0
  Serviceteedy-server:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: teedy-server
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinitionteedy-server
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetA
            - !Ref SubnetB
          SecurityGroups:
            - !Ref ContainerSecurityGroupteedy-server
