services:
  - name: default
    type: web
    env: docker
    runtime: image
    image:
      url: docker.io/joepmeneer/atomic-server:latest
    startCommand: ""
    plan: starter
    region: oregon
    envVars:
      - key: PORT
        value: "80"
    disk:
      name: default-atomic-storage
      mountPath: /atomic-storage
      sizeGB: 10
