services:
  - name: default
    type: web
    env: docker
    runtime: image
    image:
      url: docker.io/library/nginx:mainX
    startCommand: ""
    plan: starter
    region: oregon
    envVars:
      - key: REDIS_NAMESPACE
        value: mainn3
      - key: METHOD
        value: https
      - key: PORT
        value: "80"
    disk:
      name: default-usr-share-nginx-html
      mountPath: /usr/share/nginx/html
      sizeGB: 10
