services:
  - name: upsnap
    type: web
    env: docker
    runtime: image
    image:
      url: ghcr.io/seriousm4x/upsnap:4
    startCommand: ""
    plan: starter
    region: oregon
    envVars: []
    disk:
      name: upsnap-app-pb-data
      mountPath: /app/pb_data
      sizeGB: 10
