AWSTemplateFormatVersion: 2010-09-09
Description: DeployStack CFN template translated from Docker compose
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
  SubnetA:
    Type: AWS::EC2::Subnet::Id
  SubnetB:
    Type: AWS::EC2::Subnet::Id
  ServiceName:
    Type: String
    Default: DeployStackService
Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Join ['', [!Ref ServiceName, Cluster]]
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [!Ref ServiceName, ExecutionRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  LogGroupyabin:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', [/ecs/, !Ref ServiceName, TaskDefinitionyabin]]
  TaskDefinitionyabin:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - LogGroupyabin
    Properties:
      Family: !Join ['', [!Ref ServiceName, TaskDefinitionyabin]]
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 512
      Memory: 1GB
      ExecutionRoleArn: !Ref ExecutionRole
      ContainerDefinitions:
        - Name: yabin
          Image: docker.io/yureien/yabin:latest
          ReadonlyRootFilesystem: false
          PortMappings:
            - ContainerPort: 3000
          Environment: []
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroupyabin
              awslogs-stream-prefix: ecs
  ContainerSecurityGroupyabin:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['', [yabin, ContainerSecurityGroup]]
      VpcId: !Ref VPC
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0
  Serviceyabin:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: yabin
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinitionyabin
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetA
            - !Ref SubnetB
          SecurityGroups:
            - !Ref ContainerSecurityGroupyabin
  LogGroupdb:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', [/ecs/, !Ref ServiceName, TaskDefinitiondb]]
  TaskDefinitiondb:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - LogGroupdb
    Properties:
      Family: !Join ['', [!Ref ServiceName, TaskDefinitiondb]]
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 512
      Memory: 1GB
      ExecutionRoleArn: !Ref ExecutionRole
      ContainerDefinitions:
        - Name: db
          Image: docker.io/library/postgres:15-alpine
          ReadonlyRootFilesystem: false
          PortMappings: []
          Environment:
            - name: POSTGRES_USER
              value: yabin_user
            - name: POSTGRES_PASSWORD
              value: "123"
            - name: POSTGRES_DB
              value: yabin_db
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroupdb
              awslogs-stream-prefix: ecs
  ContainerSecurityGroupdb:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['', [db, ContainerSecurityGroup]]
      VpcId: !Ref VPC
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0
  Servicedb:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: db
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinitiondb
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetA
            - !Ref SubnetB
          SecurityGroups:
            - !Ref ContainerSecurityGroupdb
