services:
  - name: yabin
    type: web
    env: docker
    runtime: image
    image:
      url: docker.io/yureien/yabin:latest
    startCommand: ""
    plan: starter
    region: oregon
    envVars:
      - key: PORT
        value: "3000"
  - name: db
    type: pserv
    env: docker
    runtime: image
    image:
      url: docker.io/library/postgres:15-alpine
    startCommand: ""
    plan: starter
    region: oregon
    envVars:
      - key: POSTGRES_USER
        value: yabin_user
      - key: POSTGRES_PASSWORD
        value: "123"
      - key: POSTGRES_DB
        value: yabin_db
      - key: POSTGRES_HOST_AUTH_METHOD
        value: trust
    disk:
      name: db-var-lib-postgresql-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10
