AWSTemplateFormatVersion: 2010-09-09
Description: Deplo.my CFN template translated from Docker compose
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
  SubnetA:
    Type: AWS::EC2::Subnet::Id
  SubnetB:
    Type: AWS::EC2::Subnet::Id
  ServiceName:
    Type: String
    Default: DeployStackService
Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Join ['', [!Ref ServiceName, Cluster]]
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [!Ref ServiceName, ExecutionRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [!Ref ServiceName, TaskRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
  LogGrouptypebot-db:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', [/ecs/, !Ref ServiceName, TaskDefinitiontypebot-db]]
  TaskDefinitiontypebot-db:
    Type: AWS::ECS::TaskDefinition
    DependsOn: LogGrouptypebot-db
    Properties:
      Family: !Join ['', [!Ref ServiceName, TaskDefinitiontypebot-db]]
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 512
      Memory: 1GB
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: typebot-db
          Command: []
          Image: docker.io/postgres:16
          PortMappings: []
          Environment:
            - name: POSTGRES_DB
              value: typebot
            - name: POSTGRES_PASSWORD
              value: typebot
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGrouptypebot-db
              awslogs-stream-prefix: ecs
  ContainerSecurityGrouptypebot-db:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['', [typebot-db, ContainerSecurityGroup]]
      VpcId: !Ref VPC
      SecurityGroupIngress: []
  Servicetypebot-db:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: typebot-db
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinitiontypebot-db
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetA
            - !Ref SubnetB
          SecurityGroups:
            - !Ref ContainerSecurityGrouptypebot-db
  LogGrouptypebot-builder:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', [/ecs/, !Ref ServiceName, TaskDefinitiontypebot-builder]]
  TaskDefinitiontypebot-builder:
    Type: AWS::ECS::TaskDefinition
    DependsOn: LogGrouptypebot-builder
    Properties:
      Family: !Join ['', [!Ref ServiceName, TaskDefinitiontypebot-builder]]
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 512
      Memory: 1GB
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: typebot-builder
          Command: []
          Image: docker.io/baptistearno/typebot-builder:latest
          PortMappings:
            - ContainerPort: 8080
          Environment: []
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGrouptypebot-builder
              awslogs-stream-prefix: ecs
  ContainerSecurityGrouptypebot-builder:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['', [typebot-builder, ContainerSecurityGroup]]
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
  Servicetypebot-builder:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: typebot-builder
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinitiontypebot-builder
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetA
            - !Ref SubnetB
          SecurityGroups:
            - !Ref ContainerSecurityGrouptypebot-builder
  LogGrouptypebot-viewer:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', [/ecs/, !Ref ServiceName, TaskDefinitiontypebot-viewer]]
  TaskDefinitiontypebot-viewer:
    Type: AWS::ECS::TaskDefinition
    DependsOn: LogGrouptypebot-viewer
    Properties:
      Family: !Join ['', [!Ref ServiceName, TaskDefinitiontypebot-viewer]]
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 512
      Memory: 1GB
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: typebot-viewer
          Command: []
          Image: docker.io/baptistearno/typebot-viewer:latest
          PortMappings:
            - ContainerPort: 8081
          Environment: []
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGrouptypebot-viewer
              awslogs-stream-prefix: ecs
  ContainerSecurityGrouptypebot-viewer:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['', [typebot-viewer, ContainerSecurityGroup]]
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8081
          ToPort: 8081
          CidrIp: 0.0.0.0/0
  Servicetypebot-viewer:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: typebot-viewer
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinitiontypebot-viewer
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetA
            - !Ref SubnetB
          SecurityGroups:
            - !Ref ContainerSecurityGrouptypebot-viewer
