services:
  - name: rsshub
    type: web
    runtime: image
    image:
      url: docker.io/diygod/rsshub:latest
    startCommand: ""
    plan: starter
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: CACHE_TYPE
        value: redis
      - key: REDIS_URL
        value: redis://redis:6379/
      - key: PUPPETEER_WS_ENDPOINT
        value: ws://browserless:3000
      - key: PORT
        value: "1200"
  - name: browserless
    type: web
    runtime: image
    image:
      url: docker.io/browserless/chrome:latest
    startCommand: ""
    plan: starter
    region: oregon
    envVars:
      - key: PORT
        value: "3000"
  - name: redis
    type: web
    runtime: image
    image:
      url: docker.io/library/redis:alpine
    startCommand: ""
    plan: starter
    region: oregon
    envVars: []
    disk:
      name: redis-data
      mountPath: /data
      sizeGB: 10
