services:
  - name: default
    type: web
    env: docker
    runtime: image
    image:
      url: docker.io/library/websurfx:latest
    startCommand: ""
    plan: starter
    region: oregon
    envVars:
      - key: PORT
        value: "8080"
    disk:
      name: default-etc-xdg-websurfx-
      mountPath: /etc/xdg/websurfx/
      sizeGB: 10
