AWSTemplateFormatVersion: 2010-09-09
Description: Deplo.my CFN template translated from Docker compose
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
  SubnetA:
    Type: AWS::EC2::Subnet::Id
  SubnetB:
    Type: AWS::EC2::Subnet::Id
  ServiceName:
    Type: String
    Default: DeployStackService
Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Join ['', [!Ref ServiceName, Cluster]]
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [!Ref ServiceName, ExecutionRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [!Ref ServiceName, TaskRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
  LogGroupapp:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', [/ecs/, !Ref ServiceName, TaskDefinitionapp]]
  TaskDefinitionapp:
    Type: AWS::ECS::TaskDefinition
    DependsOn: LogGroupapp
    Properties:
      Family: !Join ['', [!Ref ServiceName, TaskDefinitionapp]]
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 512
      Memory: 1GB
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: app
          Command:
            - ""
          Image: docker.io/phlak/directory-lister:dev
          PortMappings: []
          Environment: []
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroupapp
              awslogs-stream-prefix: ecs
  ContainerSecurityGroupapp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['', [app, ContainerSecurityGroup]]
      VpcId: !Ref VPC
      SecurityGroupIngress: []
  Serviceapp:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: app
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinitionapp
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetA
            - !Ref SubnetB
          SecurityGroups:
            - !Ref ContainerSecurityGroupapp
  LogGroupmemcached:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', [/ecs/, !Ref ServiceName, TaskDefinitionmemcached]]
  TaskDefinitionmemcached:
    Type: AWS::ECS::TaskDefinition
    DependsOn: LogGroupmemcached
    Properties:
      Family: !Join ['', [!Ref ServiceName, TaskDefinitionmemcached]]
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 512
      Memory: 1GB
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: memcached
          Command:
            - ""
          Image: docker.io/library/memcached:1.6
          PortMappings: []
          Environment: []
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroupmemcached
              awslogs-stream-prefix: ecs
  ContainerSecurityGroupmemcached:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['', [memcached, ContainerSecurityGroup]]
      VpcId: !Ref VPC
      SecurityGroupIngress: []
  Servicememcached:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: memcached
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinitionmemcached
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetA
            - !Ref SubnetB
          SecurityGroups:
            - !Ref ContainerSecurityGroupmemcached
  LogGroupredis:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', [/ecs/, !Ref ServiceName, TaskDefinitionredis]]
  TaskDefinitionredis:
    Type: AWS::ECS::TaskDefinition
    DependsOn: LogGroupredis
    Properties:
      Family: !Join ['', [!Ref ServiceName, TaskDefinitionredis]]
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 512
      Memory: 1GB
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: redis
          Command:
            - ""
          Image: docker.io/library/redis:6.0
          PortMappings: []
          Environment: []
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroupredis
              awslogs-stream-prefix: ecs
  ContainerSecurityGroupredis:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['', [redis, ContainerSecurityGroup]]
      VpcId: !Ref VPC
      SecurityGroupIngress: []
  Serviceredis:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: redis
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinitionredis
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetA
            - !Ref SubnetB
          SecurityGroups:
            - !Ref ContainerSecurityGroupredis
  LogGroupnpm:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', [/ecs/, !Ref ServiceName, TaskDefinitionnpm]]
  TaskDefinitionnpm:
    Type: AWS::ECS::TaskDefinition
    DependsOn: LogGroupnpm
    Properties:
      Family: !Join ['', [!Ref ServiceName, TaskDefinitionnpm]]
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 512
      Memory: 1GB
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: npm
          Command:
            - npm
            - run
            - watch
          Image: docker.io/phlak/directory-lister:dev
          PortMappings: []
          Environment: []
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroupnpm
              awslogs-stream-prefix: ecs
  ContainerSecurityGroupnpm:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['', [npm, ContainerSecurityGroup]]
      VpcId: !Ref VPC
      SecurityGroupIngress: []
  Servicenpm:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: npm
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinitionnpm
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetA
            - !Ref SubnetB
          SecurityGroups:
            - !Ref ContainerSecurityGroupnpm
