services:
  - name: app
    type: web
    env: docker
    runtime: image
    image:
      url: docker.io/phlak/directory-lister:dev
    startCommand: ""
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: "-80"
  - name: memcached
    type: web
    env: docker
    runtime: image
    image:
      url: docker.io/library/memcached:1.6
    startCommand: ""
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: "-11211"
  - name: redis
    type: web
    env: docker
    runtime: image
    image:
      url: docker.io/library/redis:6.0
    startCommand: ""
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: "-6379"
  - name: npm
    type: web
    env: docker
    runtime: image
    image:
      url: docker.io/phlak/directory-lister:dev
    startCommand: npm run watch
    plan: free
    region: oregon
    envVars: []
