AWSTemplateFormatVersion: 2010-09-09
Description: DeployStack CFN template translated from Docker compose
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
  SubnetA:
    Type: AWS::EC2::Subnet::Id
  SubnetB:
    Type: AWS::EC2::Subnet::Id
  ServiceName:
    Type: String
    Default: DeployStackService
Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Join ['', [!Ref ServiceName, Cluster]]
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [!Ref ServiceName, ExecutionRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  LogGroupnginx:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', [/ecs/, !Ref ServiceName, TaskDefinitionnginx]]
  TaskDefinitionnginx:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - LogGroupnginx
    Properties:
      Family: !Join ['', [!Ref ServiceName, TaskDefinitionnginx]]
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 512
      Memory: 1GB
      ExecutionRoleArn: !Ref ExecutionRole
      ContainerDefinitions:
        - Name: nginx
          Image: docker.io/library/nginx:1-alpine
          ReadonlyRootFilesystem: false
          PortMappings:
            - ContainerPort: 80
          Environment:
            - name: PROTOCOL
              value: some-nice-value
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroupnginx
              awslogs-stream-prefix: ecs
  ContainerSecurityGroupnginx:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['', [nginx, ContainerSecurityGroup]]
      VpcId: !Ref VPC
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0
  Servicenginx:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: nginx
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinitionnginx
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetA
            - !Ref SubnetB
          SecurityGroups:
            - !Ref ContainerSecurityGroupnginx
