services:
  - name: default
    type: web
    runtime: image
    image:
      url: docker.io/library/nginx:latest
    startCommand: ""
    plan: starter
    region: oregon
    envVars:
      - key: PORT
        value: "80"
