services:
  - name: default
    type: web
    env: docker
    runtime: image
    image:
      url: docker.io/xemle/home-gallery:latest
    startCommand: ""
    plan: starter
    region: oregon
    envVars:
      - key: PORT
        value: "3000"
    disk:
      name: default-data
      mountPath: /data
      sizeGB: 10
