services:
  - name: mirotalkc2c
    type: web
    env: docker
    runtime: image
    image:
      url: docker.io/mirotalk/c2c:latest
    startCommand: ""
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: null
