
{{- range $key, $service := .Values.services }}
{{- if $service.enabled }}
{{- if $service.environment.sensitive }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deploystack.fullname" $ }}-{{ $key }}-secret
  labels:
    {{- include "deploystack.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $key }}
type: Opaque
data:
  {{- range $envKey, $envValue := $service.environment.sensitive }}
  {{ $envKey }}: {{ $envValue | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
