global:
  nameOverride: ""
  fullnameOverride: ""
  imagePullSecrets: []
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
services:
  default:
    enabled: true
    replicaCount: 1
    image:
      repository: docker.io/library/nginx
      pullPolicy: IfNotPresent
      tag: first2
    service:
      type: ClusterIP
      ports:
        - port: 5244
          targetPort: 5244
          protocol: TCP
    environment:
      regular:
        pipi: nie jest
      sensitive: {}
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
    volumes:
      - name: default-opt-alist-data
        mountPath: /opt/alist/data
        hostPath: /etc/alist
dependencies: {}
